#spring:
#  datasource:
#    username: root
#    password: 425658167
#    url: jdbc:mysql://192.168.56.10:3306/PMS
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: 1765a952-5b9a-4fee-9e20-51ae42d736cc
#        group: dev
#    alicloud:
#      access-key: <your access key>
#      secret-key: <your secret key>
#      oss:
#        endpoint: https://oss-cn-beijing.aliyuncs.com
#    util:
#      enabled: false
#  config:
#    import:
#      - nacos:nacos-config-example.properties?refresh=true
#  application:
#    name: product
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  thymeleaf:
#    cache: false
#  mvc:
#    static-path-pattern: /static/**
#  redis:
#    host: 192.168.56.10
#    port: 6379
#  cache:
#    type: redis
#    redis:
#      time-to-live: 60000
#      use-key-prefix: true
#      cache-null-values: true
#  session:
#    store-type: redis
#thellumall:
#  thread:
#    max-size: 200
#    core-size: 20
#    keep-alive-time: 10
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server:
#  port: 10000
#
#
#
