#spring:
#  datasource:
#    username: root
#    password: 425658167
#    url: jdbc:mysql://192.168.56.10:3306/OMS
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: 22221e13-393d-4683-b76d-dc0ddd1adcbb
#        group: dev
#  config:
#    import:
#      - nacos:nacos-config-example.properties?refresh=true
#  application:
#    name: order
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  rabbitmq:
#    host: 192.168.56.10
#    port: 5672
#    virtual-host: /s
#    publisher-confirm-type: correlated
#    publisher-returns: true
#    template:
#      mandatory: true
#    listener:
#      simple:
#        acknowledge-mode: manual
#alibaba:
#  cloud:
#    access-key: <your access key>
#    secret-key: <your secret key>
#    oss:
#      endpoint: https://oss-cn-beijing.aliyuncs.com
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server:
#  port: 9000
