#spring:
#  datasource:
#    username: root
#    password: 425658167
#    url: jdbc:mysql://192.168.56.10:3306/UMS
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: d07fc334-107c-4d4f-a427-8bc96d29610a
#        group: dev
#  config:
#    import:
#      - nacos:nacos-config-example.properties?refresh=true
#  application:
#    name: member
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#alibaba:
#  cloud:
#    access-key: <your access key>
#    secret-key: <your secret key>
#    oss:
#      endpoint: https://oss-cn-beijing.aliyuncs.com
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server:
#  port: 8000
