#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: product_route
#          uri: lb://product
#          predicates:
#            - Path=/api/product/**
#          filters:
#            - RewritePath=/api/?(?<segment>.*), /$\{segment}
#
#        - id: third_party_route
#          uri: lb://thirdParty
#          predicates:
#            - Path=/api/thirdparty/**
#          filters:
#            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}
#
#        - id: member_route
#          uri: lb://member
#          predicates:
#            - Path=/api/member/**
#          filters:
#            - RewritePath=/api/?(?<segment>.*), /$\{segment}
#
#        - id: warehouse_route
#          uri: lb://warehouse
#          predicates:
#            - Path=/api/warehouse/**
#          filters:
#            - RewritePath=/api/?(?<segment>.*), /$\{segment}
#
#        - id: admin_route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
#
#        - id: thellumall_host_route
#          uri: lb://product
#          predicates:
#            - Host=thellumall.com, item.thellumall.com
#
#        - id: thellumall_search_route
#          uri: lb://search
#          predicates:
#            - Host=search.thellumall.com
#
#        - id: thellumall_auth_route
#          uri: lb://auth
#          predicates:
#            - Host=auth.thellumall.com
#
#        - id: thellumall_cart_route
#          uri: lb://cart
#          predicates:
#            - Host=cart.thellumall.com
#
#        - id: thellumall_order_route
#          uri: lb://order
#          predicates:
#            - Host=order.thellumall.com
#
#        - id: thellumall_member_route
#          uri: lb://member
#          predicates:
#            - Host=member.thellumall.com
### front end use api prefix
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: gateway
#
#server:
#  port: 88
#
#
