/*Table structure for table `sys_menu` */

DROP TABLE IF EXISTS `sys_menu`;

CREATE TABLE `sys_menu`
(
    `menu_id` bigint(20) NOT NULL AUTO_INCREMENT,
    `parent_id` bigint(20) DEFAULT NULL COMMENT 'Parent menu ID, first-level menu is 0',
    `name` varchar(50) DEFAULT NULL COMMENT 'menu name',
    `url` varchar(200) DEFAULT NULL COMMENT 'Menu URL',
    `perms` varchar(500) DEFAULT NULL COMMENT 'Authorization (multiple separated by commas, such as: user:list,user:create)',
    `type` int(11) DEFAULT NULL COMMENT 'Type 0: Directory 1: Menu 2: Button',
    `icon` varchar(50) DEFAULT NULL COMMENT 'menu icon',
    `order_num` int(11) DEFAULT NULL COMMENT 'sort',
    PRIMARY KEY (`menu_id`)
) ENGINE=InnoDB AUTO_INCREMENT=76 DEFAULT CHARSET=utf8mb4 COMMENT='Menu Management';

/*Data for the table `sys_menu` */

insert into `sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`)
values (1, 0, 'system management', NULL, NULL, 0, 'system', 0),
       (2, 1, 'Administrator list', 'sys/user', NULL, 1, 'admin', 1),
       (3, 1, 'role management', 'sys/role', NULL, 1, 'role', 2),
       (4, 1, 'menu management', 'sys/menu', NULL, 1, 'menu', 3),
       (5, 1, 'SQL monitoring', 'http://localhost:8080/renren-fast/druid/sql.html', NULL, 1, 'sql', 4),
       (6, 1, 'scheduled task', 'job/schedule', NULL, 1, 'job', 5),
       (7, 6, 'View', NULL, 'sys:schedule:list,sys:schedule:info', 2, NULL, 0),
       (8, 6, 'Add', NULL, 'sys:schedule:save', 2, NULL, 0),
       (9, 6, 'modify', NULL, 'sys:schedule:update', 2, NULL, 0),
       (10, 6, 'delete', NULL, 'sys:schedule:delete', 2, NULL, 0),
       (11, 6, 'pause', NULL, 'sys:schedule:pause', 2, NULL, 0),
       (12, 6, 'resume', NULL, 'sys:schedule:resume', 2, NULL, 0),
       (13, 6, 'Execute immediately', NULL, 'sys:schedule:run', 2, NULL, 0),
       (14, 6, 'log list', NULL, 'sys:schedule:log', 2, NULL, 0),
       (15, 2, 'View', NULL, 'sys:user:list,sys:user:info', 2, NULL, 0),
       (16, 2, 'New', NULL, 'sys:user:save,sys:role:select', 2, NULL, 0),
       (17, 2, 'Modify', NULL, 'sys:user:update,sys:role:select', 2, NULL, 0),
       (18, 2, 'delete', NULL, 'sys:user:delete', 2, NULL, 0),
       (19, 3, 'View', NULL, 'sys:role:list,sys:role:info', 2, NULL, 0),
       (20, 3, 'New', NULL, 'sys:role:save,sys:menu:list', 2, NULL, 0),
       (21, 3, 'modify', NULL, 'sys:role:update,sys:menu:list', 2, NULL, 0),
       (22, 3, 'delete', NULL, 'sys:role:delete', 2, NULL, 0),
       (23, 4, 'View', NULL, 'sys:menu:list,sys:menu:info', 2, NULL, 0),
       (24, 4, 'New', NULL, 'sys:menu:save,sys:menu:select', 2, NULL, 0),
       (25, 4, 'Modify', NULL, 'sys:menu:update,sys:menu:select', 2, NULL, 0),
       (26, 4, 'delete', NULL, 'sys:menu:delete', 2, NULL, 0),
       (27, 1, 'Parameter management', 'sys/config',
        'sys:config:list,sys:config:info,sys:config:save,sys:config:update,sys:config:delete', 1, 'config', 6),
       (29, 1, 'system log', 'sys/log', 'sys:log:list', 1, 'log', 7),
       (30, 1, 'File upload', 'oss/oss', 'sys:oss:all', 1, 'oss', 6),
       (31, 0, 'Product system', '', '', 0, 'editor', 0),
       (32, 31, 'Category maintenance', 'product/category', '', 1, 'menu', 0),
       (34, 31, 'Brand management', 'product/brand', '', 1, 'editor', 0),
       (37, 31, 'Platform properties', '', '', 0, 'system', 0),
       (38, 37, 'Attribute  group', 'product/attrgroup', '', 1, 'tubiao', 0),
       (39, 37, 'Specification parameters', 'product/baseattr', '', 1, 'log', 0),
       (40, 37, 'sales attribute', 'product/saleattr', '', 1, 'zonghe', 0),
       (41, 31, 'product maintenance', 'product/spu', '', 0, 'zonghe', 0),
       (42, 0, 'Preferential marketing', '', '', 0, 'mudedi', 0),
       (43, 0, 'inventory system', '', '', 0, 'shouye', 0),
       (44, 0, 'Order System', '', '', 0, 'config', 0),
       (45, 0, 'User system', '', '', 0, 'admin', 0),
       (46, 0, 'content management', '', '', 0, 'sousuo', 0),
       (47, 42, 'coupon management', 'coupon/coupon', '', 1, 'zhedie', 0),
       (48, 42, 'Issuance record', 'coupon/history', '', 1, 'sql', 0),
       (49, 42, 'special event', 'coupon/subject', '', 1, 'tixing', 0),
       (50, 42, 'Seckill', 'coupon/seckill', '', 1, 'daohang', 0),
       (51, 42, 'Points Maintenance', 'coupon/bounds', '', 1, 'geren', 0),
       (52, 42, 'coupon/full', 'coupon/full', '', 1, 'shoucang', 0),
       (53, 43, 'warehouse maintenance', 'ware/wareinfo', '', 1, 'shouye', 0),
       (54, 43, 'Inventory work order', 'ware/task', '', 1, 'log', 0),
       (55, 43, 'product inventory', 'ware/sku', '', 1, 'jiesuo', 0),
       (56, 44, 'order query', 'order/order', '', 1, 'zhedie', 0),
       (57, 44, 'Return order processing', 'order/return', '', 1, 'shanchu', 0),
       (58, 44, 'level rules', 'order/settings', '', 1, 'system', 0),
       (59, 44, 'Payment flow query', 'order/payment', '', 1, 'job', 0),
       (60, 44, 'Refund flow query', 'order/refund', '', 1, 'mudedi', 0),
       (61, 45, 'member list', 'member/member', '', 1, 'geren', 0),
       (62, 45, 'membership level', 'member/level', '', 1, 'tubiao', 0),
       (63, 45, 'integral change', 'member/growth', '', 1, 'bianji', 0),
       (64, 45, 'statistics', 'member/statistics', '', 1, 'sql', 0),
       (65, 46, 'Home page recommendation', 'content/index', '', 1, 'shouye', 0),
       (66, 46, 'popular categories', 'content/category', '', 1, 'zhedie', 0),
       (67, 46, 'Comment Management', 'content/comments', '', 1, 'pinglun', 0),
       (68, 41, 'spu management', 'product/spu', '', 1, 'config', 0),
       (69, 41, 'release product', 'product/spuadd', '', 1, 'bianji', 0),
       (70, 43, 'Purchase Order Maintenance', '', '', 0, 'tubiao', 0),
       (71, 70, 'Purchase requirements', 'ware/purchaseitem', '', 1, 'editor', 0),
       (72, 70, 'Purchase Order', 'ware/purchase', '', 1, 'menu', 0),
       (73, 41, 'product management', 'product/manager', '', 1, 'zonghe', 0),
       (74, 42, 'member price', 'coupon/memberprice', '', 1, 'admin', 0),
       (75, 42, 'Daily Flash Kill', 'coupon/seckillsession', '', 1, 'job', 0);
