spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
  session:
    store-type: redis
  application:
    name: search
server:
  port: 12000
