#spring:
#  datasource:
#    username: root
#    password: 425658167
#    url: jdbc:mysql://192.168.56.10:3306/SMS
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: 7201755b-6f7f-4300-8d26-eea32695c636
#        group: dev
#    alicloud:
#      access-key: <your access key>
#      secret-key: <your secret key>
#      oss:
#        endpoint: https://oss-cn-beijing.aliyuncs.com
#    util:
#      enabled: false
#  config:
#    import:
#      - nacos:nacos-config-example.properties?refresh=true
#  application:
#    name: coupon
#
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server:
#  port: 7000
#
